name: "publish"
on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/publish.yml"
      - "public/**"
      - "index.html"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Configure
        run: |
          sed -i '4i import axios from "axios"' src/main.js
          sed -i '5i axios.defaults.baseURL = "${{ secrets.TINYOAUTH_WEBUI_HOST }}"' src/main.js

      - name: Build
        run: |
          npm install
          npm run build

      - name: Install ssh-key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Publish to EC2
        run: |
          ssh-keyscan -H "${{ secrets.TARGET_SERVER }}" >> ~/.ssh/known_hosts
          rsync -r dist ubuntu@${{ secrets.TARGET_SERVER }}:~

      - name: Delete ssh-key
        run: rm ~/.ssh/id_ed25519
